### ISSUE TITLE
Dropdown not remembering settings

### ISSUE THREAD

**Issue by NikRimington** [umco/umbraco-stacked-content#17] opened 2017-05-11 22:03 UTC
Hi guys,

Got a bit of strange error that I can't suss out.
When re-opening a page that hs been saved and published, if I go to edit a stacked content block that has a drop down on it the fails to select the correct element. 
![image](https://cloud.githubusercontent.com/assets/13313745/25973856/ce2a351a-369d-11e7-88ed-df26182b5bdd.png)

Having investigated when the Umbraco controller gets called to set the drop down, it looks like the model is storing the text value of the drop down instead of the id value. 

### Settings
Windows 10 Creators update
Visual studio 2015
Empty web project - .Net 4.6.1
Umbraco 7.5.13 (installed via nuget)
Stacked content - 1.0.4 (installed via nuget)
(No starter kit)

### Reproduction steps
Assuming the blank setup above:

1) Create a dropdown with mutliple entries in it (test run had 3)
2) Create new document type and add drop down to document type
3) Create second document type for use in stacked content with same dropdown added.
4) Create stacked content data type using document type created in step 3
5) Add stacked content data type from step 4 to document type in step 2
6) Create node in website using document type from step 2 - This should have two properties on it. One that is the basic drop down, the second being stacked content.
7) Set the drop down in the first property, then add an entry to the stacked content property.
8) Save / save and publish document
9) Stop website or close browser
10) Restart website or re-open browser and go back to edit the created content node
11) Edit the stacked content, the drop down may or may not be set at this point.
12) If it is set, change the value of the drop down, save the page again, then go back and edit it. This time the drop down is most likely blank.

### Additional notes
During my investigation I put a breakpoint on line 10813 of the Umbraco.Controller.js file (if $scope.model.value === null ........). When examining the value of items when opening the editor for the stacked content entry I found that my $scope.model.value had a value equal to the text value of the drop down, where as the angular view for the drop down is trying to match the ID of the entries. As a result this fails.
![image](https://cloud.githubusercontent.com/assets/13313745/25973788/7d24752c-369d-11e7-8b96-a5d782b6aaa7.png)

![image](https://cloud.githubusercontent.com/assets/13313745/25973816/afed096a-369d-11e7-83f2-6b11727860f6.png)

This has occurred on another site running Umbraco 7.5.8 and .Net 4.5.2

**Comment by leekelleher** [comment] 2017-05-12 08:45
@NikRimington Thanks for the thorough report, it's very much appreciated! 😃 

I recall Nested Content having issues with the DropdownList editor, but not sure what the outcome was. We'll take a look into it.

**Comment by RJPhillips01** [comment] 2018-04-03 11:35
Hi - just wondering what the status is with this stacked content drop down list issue?

**Comment by leekelleher** [comment] 2018-04-04 14:50
I hadn't followed up on this one.  To be honest, I've never had much success with the default Dropdown List editors, we tend to use our own one ([dictionary dropdown](https://github.com/leekelleher/umbraco-dictionary-dropdown) - it doesn't rely on the prevalue IDs).  Which has worked fine for our needs (over the past 4 years).

Now, being a curious developer, I wanted to see where the problem here happens.  I've spent about 5 hours today reproducing the issue, digging deep into Umbraco core - I gotta say, it's a weird one.

The problem happens immediately after the page is published.  Any editors within Stacked Content that use prevalue IDs get their value replaced with the "published" value.  I still can't pinpoint where this actually happens.  I mean, I know where the prevalue ID is replaced with the published value, ([it's here](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/PropertyEditors/PublishValueValueEditor.cs#L40)) ... but I don't know how that value updates Stacked Content.

I'll take another look at it soon... but I'm not sure how many hours I can burn on it. 😕

**Comment by RJPhillips01** [comment] 2018-04-05 09:35
Thanks Lee - I appreciate you looking into it but please don't "burn" too many hours on this - It's not a big problem for me I was just wondering what the latest was. I may take a look at your dictionary dropdown - thanks for noting that.

All the best, Rich.

**Comment by leekelleher** [comment] 2018-04-05 09:38
OK, we made a break through 🎉 ... _and in the name of transparency,_ it looks that we've got a long-standing bug in InnerContent - see here for more details: https://github.com/umco/umbraco-inner-content/pull/25

**Comment by NikRimington** [comment] 2018-04-05 10:42
I'm so excited that this looks like it might be getting resolved 🎉 🎉 🎉 
Wish I could have been smart enough to find the issue and provide more help on it!

**Comment by leekelleher** [comment] 2018-04-23 14:47
Follow up on this, since merging in the fix - re: https://github.com/umco/umbraco-inner-content/pull/25
We've released InnerContent v1.1.1 - so it's [upgradeable from NuGet](https://www.nuget.org/packages/Our.Umbraco.InnerContent/1.1.1) (or Our Umbraco project page).

I'll close this ticket off.

**Closed by leekelleher** 2018-04-23 14:47 UTC
Labels: bug
