### ISSUE TITLE
Nested Stack Content don't show Tab content

### ISSUE THREAD

**Issue by JcRichards1991** [umco/umbraco-stacked-content#23] opened 2017-11-23 10:46 UTC
On Umbraco v7.7.6 with StackedContent v1.0.4

When having Stacked Content within Stacked Content, at each depth, the tabs for the content being displayed in the overview panel has an id of 20, therefore, the active class is not being applied to the tab and no properties are being displayed.

I've put in a workaround within innercontent.controllers.js to randomly generate a number, and using said number for the id:

```
self.extendEditorModel = function(editorModel, dbModel) {

            editorModel.key = dbModel && dbModel.key ? dbModel.key : editorModel.key;
            editorModel.name = dbModel && dbModel.name ? dbModel.name : editorModel.name;

            if (!editorModel.key) {
                editorModel.key = self.generateUid();
            }

            /*  Begin Custom Code   */
            for (var t = 0; t < editorModel.tabs.length; t++) {
                var tab = editorModel.tabs[t];
                var randomNumber = Math.ceil(Math.random() * 1000)
                tab.id = randomNumber;
            }
            /* End Custom Code  */

            if (dbModel) {
                for (var t = 0; t < editorModel.tabs.length; t++) {
                    var tab = editorModel.tabs[t];
                    for (var p = 0; p < tab.properties.length; p++) {
                        var prop = tab.properties[p];
                        if (dbModel.hasOwnProperty(prop.alias)) {
                            prop.value = dbModel[prop.alias];
                        }
                    }
                }
            }

            return editorModel;

        }
```

Not sure if this is the best approach to the issue, but for the meantime it works

**Comment by leekelleher** [comment] 2018-04-23 15:00
@JcRichards1991 I had some time to follow up on outstanding issues.  I've had a test around with a couple of nested StackedContents, but I couldn't reproduce the issue.  How many levels deep did you say it happens at?

I'd be great to know if the ID "20" happens on the InnerContent side or Umbraco side.

**Comment by JcRichards1991** [comment] 2018-05-01 09:29
@leekelleher I was experiencing this from 1 level deep see this gif
![stackedcontent](https://user-images.githubusercontent.com/17648147/39468350-793858c6-4d2a-11e8-9817-9e5fa1781834.gif)

**Comment by leekelleher** [comment] 2018-05-01 09:36
Thanks for the gif @JcRichards1991! Is this still on versions: Umbraco v7.7.6 & StackedContent v1.0.4?
As I've tried with a nested StackedContent on latest Umbraco and it loads the edits panel. Thanks.

**Comment by JcRichards1991** [comment] 2018-05-08 13:02
@leekelleher - no worries, thought it was the best way to show the issue.

Yes, Still on version 7.7.6 of umbraco (assembly version 1.0.6528.26344) & version 1.0.4 of stacked content:

![image](https://user-images.githubusercontent.com/17648147/39758669-73cf0fd0-52c8-11e8-8f63-8ef03ef259ed.png)

**Comment by leekelleher** [comment] 2018-05-08 15:25
Thanks for the update @JcRichards1991.

I've tried a fresh install of Umbraco v7.7.6 with StackedContent v1.0.4, then set-up a basic structure - similar to the one in your GIF above, but I can't reproduce the issue. The nested SC items open fine for me.

I'll try test a bit deeper, see what I can find.

In the meantime, could there be any other packages that might be interfering with the overlay? (trying to rule anything out)

**Comment by leekelleher** [comment] 2018-05-08 15:38
I've tested at 5 levels-deep, and that appears to work fine for me.

I tested it against Chrome 66, IE11 and Edge - all worked as expected. (Although I doubt this is a browser concern, because of the the ID=20 issue.

At this point, I'm out of ideas.

**Comment by leekelleher** [comment] 2018-05-08 16:05
@JcRichards1991 OK, I think I've figured out how to reproduce it.  It's to do with DocType Compositions.

If a tab is defined on a composition, then applied to a doctype - which if further properties are added to that inherited tab, (on the doctype, not composition), then the "ID" for that tab is taken from the composition, not the doctype itself. (Which is where your "20" value is coming from)

I'm investigating whether there's anything we can do with the `umb-tabs-nav` directive to make to resolve this. _Watch this space._

**Comment by leekelleher** [comment] 2018-05-08 16:46
OK, I think I've got a potential fix. The `umb-tabs-nav` has a parameter for `id-suffix`, so we can append _something_ to the end of each ID.

I'll put a patch in for InnerContent and discuss with @mattbrailsford.

**Comment by leekelleher** [comment] 2018-05-08 17:12
Closing this ticket, a proposed patch is available for InnerContent, https://github.com/umco/umbraco-inner-content/pull/27

**Closed by leekelleher** 2018-05-08 17:12 UTC
Labels: umbraco
